"""empty message

Revision ID: 696c1881ff7a
Revises: 
Create Date: 2021-05-13 21:01:31.993395

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '696c1881ff7a'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('person',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('lastName', sa.String(length=80), nullable=False),
    sa.Column('age', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('relationships',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('children',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('personID', sa.Integer(), nullable=False),
    sa.Column('childID', sa.Integer(), nullable=False),
    sa.Column('relationshipID', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['childID'], ['person.id'], ),
    sa.ForeignKeyConstraint(['personID'], ['person.id'], ),
    sa.ForeignKeyConstraint(['relationshipID'], ['relationships.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('personID')
    )
    op.create_table('parents',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('personID', sa.Integer(), nullable=False),
    sa.Column('parentID', sa.Integer(), nullable=False),
    sa.Column('relationshipID', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['parentID'], ['person.id'], ),
    sa.ForeignKeyConstraint(['personID'], ['person.id'], ),
    sa.ForeignKeyConstraint(['relationshipID'], ['relationships.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('personID')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('parents')
    op.drop_table('children')
    op.drop_table('relationships')
    op.drop_table('person')
    # ### end Alembic commands ###
