"""empty message

Revision ID: 6e674d1ab417
Revises: 
Create Date: 2021-05-15 11:06:15.190496

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6e674d1ab417'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('person',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('lastName', sa.String(length=80), nullable=False),
    sa.Column('age', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('relationships',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('relative',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('personID', sa.Integer(), nullable=False),
    sa.Column('relativeID', sa.Integer(), nullable=False),
    sa.Column('relationshipID', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['personID'], ['person.id'], ),
    sa.ForeignKeyConstraint(['relationshipID'], ['relationships.id'], ),
    sa.ForeignKeyConstraint(['relativeID'], ['person.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('relative')
    op.drop_table('relationships')
    op.drop_table('person')
    # ### end Alembic commands ###
